name = "cf-workers-telegram-bot"
main = "dist/worker.mjs"

account_id = "103b3fa94dce0b8ef9905e1a43e44a27"
workers_dev = true
compatibility_date = "2022-02-16"

build.command = "npm install && npm run build"
