name = "cf-workers-telegram-bot"
main = "dist/worker.mjs"

account_id = "23c057184e5048b737a21750c043a9b8"
workers_dev = true
compatibility_date = "2022-02-16"

build.command = "npm install && npm run build"
